In [55]:
import glob
import os

# What are the "patient" files.

In [52]:
patient_files = glob.glob('../../data/raw/Transactions/patients_*.txt')
patient_files[:5]

['../../data/raw/Transactions\\patients_1.txt',
 '../../data/raw/Transactions\\patients_10.txt',
 '../../data/raw/Transactions\\patients_11.txt',
 '../../data/raw/Transactions\\patients_12.txt',
 '../../data/raw/Transactions\\patients_13.txt']

Prescribed drugs including the periods and repeats for each drug for an individual.

In [74]:
patient_data = pd.read_csv('../../data/raw/Transactions\\patients_1.txt', sep='\t', parse_dates = ['Dispense_Week'])
patient_data.head()

,Patient_ID,Store_ID,Prescriber_ID,Drug_ID,SourceSystem_Code,Prescription_Week,Dispense_Week,Drug_Code,NHS_Code,IsDeferredScript,Script_Qty,Dispensed_Qty,MaxDispense_Qty,PatientPrice_Amt,WholeSalePrice_Amt,GovernmentReclaim_Amt,RepeatsTotal_Qty,RepeatsLeft_Qty,StreamlinedApproval_Code
0,1,2739,26728,8208,F,2010-08-15,2011-01-02,SPIR3,8626B,0,30,2,NaN,5.6,61.51,71.29,6,4,NaN
1,1,2739,26728,6085,F,2010-09-05,2011-01-23,NUEL1,8230E,0,100,2,NaN,5.6,4.80,6.56,6,4,NaN
2,1,2739,26728,763,F,2010-10-31,2011-01-23,ATAC1,8295N,0,30,2,NaN,5.6,10.73,13.65,6,4,NaN
3,1,2739,26728,6481,F,2011-01-02,2011-01-30,PANT14,8008L,0,60,2,NaN,5.6,42.24,47.56,6,4,NaN
4,1,2739,26728,8208,F,2010-08-15,2011-01-30,SPIR3,8626B,0,30,3,NaN,5.6,61.51,71.29,6,3,NaN

# What are the "lookup" files provided

In [54]:
lookup_files = glob.glob('../../data/raw/Lookups/*.txt')
lookup_files

['../../data/raw/Lookups\\ATC_LookUp.txt',
 '../../data/raw/Lookups\\ChronicIllness_LookUp.txt',
 '../../data/raw/Lookups\\Drug_LookUp.txt',
 '../../data/raw/Lookups\\patients.txt',
 '../../data/raw/Lookups\\stores.txt']

## atc_lookup: a classification mapping? 

Seems that it could be the Anatomical Therapeutic Chemical Classification System

The Anatomical Therapeutic Chemical (ATC) Classification System is used for the classification of active ingredients of drugs according to the organ or system on which they act and their therapeutic, pharmacological and chemical properties. It is controlled by the World Health Organization Collaborating Centre for Drug Statistics Methodology (WHOCC), and was first published in 1976.[1]

In [65]:
atc_lookup = pd.read_csv('../../data/raw/Lookups/ATC_LookUp.txt', sep='\t')
atc_lookup.head()

,ATCLevel1Code,ATCLevel1Name,ATCLevel2Code,ATCLevel2Name,ATCLevel3Code,ATCLevel3Name,ATCLevel4Code,ATCLevel4Name,ATCLevel5Code,ATCLevel5Name
0,A,ALIMENTARY TRACT AND METABOLISM,A01,STOMATOLOGICAL PREPARATIONS,A01A,STOMATOLOGICAL PREPARATIONS,A01AB,ANTIINFECTIVES AND ANTISEPTICS FOR LOCAL ORAL ...,A01AB03,CHLORHEXIDINE
1,A,ALIMENTARY TRACT AND METABOLISM,A01,STOMATOLOGICAL PREPARATIONS,A01A,STOMATOLOGICAL PREPARATIONS,A01AB,ANTIINFECTIVES AND ANTISEPTICS FOR LOCAL ORAL ...,A01AB04,AMPHOTERICIN B
2,A,ALIMENTARY TRACT AND METABOLISM,A01,STOMATOLOGICAL PREPARATIONS,A01A,STOMATOLOGICAL PREPARATIONS,A01AB,ANTIINFECTIVES AND ANTISEPTICS FOR LOCAL ORAL ...,A01AB08,NEOMYCIN
3,A,ALIMENTARY TRACT AND METABOLISM,A01,STOMATOLOGICAL PREPARATIONS,A01A,STOMATOLOGICAL PREPARATIONS,A01AB,ANTIINFECTIVES AND ANTISEPTICS FOR LOCAL ORAL ...,A01AB11,VARIOUS
4,A,ALIMENTARY TRACT AND METABOLISM,A01,STOMATOLOGICAL PREPARATIONS,A01A,STOMATOLOGICAL PREPARATIONS,A01AC,CORTICOSTEROIDS FOR LOCAL ORAL TREATMENT,A01AC03,HYDROCORTISONE

## chronic_illness_lookup: a mapping of a particular illness to specific "master" product.

In [66]:
chronic_illness_lookup = pd.read_csv('../../data/raw/Lookups\\ChronicIllness_LookUp.txt', sep='\t')
chronic_illness_lookup.head()

  ChronicIllness  MasterProductID              MasterProductFullName
0       Diabetes              141        ACTOS TAB 30MG (AS HCL) 28
1       Diabetes              142        ACTOS TAB 45MG (AS HCL) 28
2   Osteoporosis              146  ACTONEL ONCE-A-MONTH TAB 150MG 1
3   Osteoporosis              267            ALENDROBELL TAB 70MG 4
4   Osteoporosis              269       ALENDRONATE (GA) TAB 70MG 4

## drug_lookup: a mapping from a master product to finer grained detail about its content?

In [68]:
drug_lookup = pd.read_csv('../../data/raw/Lookups/Drug_LookUp.txt', sep='\t')
drug_lookup.head()

,MasterProductID,MasterProductCode,MasterProductFullName,BrandName,FormCode,StrengthCode,PackSizeNumber,GenericIngredientName,EthicalSubCategoryName,EthicalCategoryName,ManufacturerCode,ManufacturerName,ManufacturerGroupID,ManufacturerGroupCode,ChemistListPrice,ATCLevel5Code,ATCLevel4Code,ATCLevel3Code,ATCLevel2Code,ATCLevel1Code
0,7777,SCH4,SQUIBB HC OINT 1% 50G 1,SQUIBB HC,OINT,1% 50G,1.0,HYDROCORTISONE ACETATE,NON PBS Substitutable,ETHICAL NON PBS,BQ,BRISTOL-MYERS SQUIBB AUST,43,BMS,1.8609,A07EA,A07EA,A07E,A07,A
1,9276,ZA13,ZANTAC TAB 300MG 30,ZANTAC,TAB,300MG,30.0,RANITIDINE,PBS Substitutable,ETHICAL PBS,AS,ASPEN PHARMACARE AUSTRALI,23,ASPEN,6.1300,A02BA02,A02BA,A02B,A02,A
2,5465,MIXT1,THE MIXTURE 200,THE MIXTURE,NaN,NaN,200.0,Not Applicable,Unknown Sub-Category,ETHICAL NON PBS,NaN,Not Applicable,-1,Not Applicable,8.6174,NaN,NaN,NaN,NaN,NaN
3,12555,METO45,METOPROLOL (AN) TAB 100MG 60,METOPROLOL (AN),TAB,100MG,60.0,METOPROLOL TARTRATE,PBS Generic,ETHICAL PBS,EA,AMNEAL PHARMACEUTICALS PT,268,AMNEAL PHARMACEUTICALS PT,2.4200,C07AB02,C07AB,C07A,C07,C
4,7671,S/P2,S/P COLD & FLU TAB 24 24,S/P COLD & FLU,TAB,NaN,24.0,PSEUDOEPHEDRINE + OTHER,Unknown Sub-Category,ETHICAL NON PBS,NaN,Not Applicable,-1,Not Applicable,0.0000,NaN,NaN,NaN,NaN,NaN

## patients_lookup: patient meta data

In [76]:
patients_lookup = pd.read_csv('../../data/raw/Lookups/patients.txt', sep='\t')
patients_lookup.head()

   Patient_ID gender  year_of_birth  postcode
0           1      F           1900      2516
1           2      F           1935      3042
2           3      M           1900      4750
3           4      U           1900      2765
4           5      U           1900      2229

## stores_lookup: store meta data

In [82]:
stores_lookup = pd.read_csv('../../data/raw/Lookups/stores.txt', sep='\t')
stores_lookup.head()

   Store_ID StateCode  postcode  IsBannerGroup
0         1       VIC    3558.0              0
1         2       VIC    3124.0              0
2         3        WA    6107.0              1
3         4       VIC    3214.0              0
4         5       VIC    3172.0              0

# Collected data

## postcode_lookup: map from postcode to locations and some other meta data

In [85]:
postcode_lookup = pd.read_csv('../../data/extra/Australian_Post_Codes_Lat_Lon.csv')
postcode_lookup.head()

,postcode,suburb,state,dc,type,lat,lon
0,200,AUSTRALIAN NATIONAL UNIVERSITY,ACT,AUSTRALIAN NATIONAL UNI LPO,Post Office Boxes,-35.277272,149.117136
1,221,BARTON,ACT,NaN,LVR,-35.201372,149.095065
2,800,DARWIN,NT,DARWIN DELIVERY CENTRE,Delivery Area,-12.801028,130.955789
3,801,DARWIN,NT,DARWIN DELIVERY CENTRE,Post Office Boxes,-12.801028,130.955789
4,804,PARAP,NT,PARAP,Post Office Boxes,-12.432181,130.843310

## Refer to this site:

http://www.abs.gov.au/websitedbs/censushome.nsf/home/data?opendocument